### ISSUE TITLE
Счет цикла начинается не с нуля

### ISSUE THREAD

**Issue by MaratGP1967** [MaratGP1967/javaqa-team-diplom#1]
# Описание
Счетчик цикла (стр.35) и параметр get(i-1) (стр.36) должны иметь значение ноль в методе `containsGame(Game game)` класса `GameStore`
# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/4a30451cf2f4132fa063af5bd1a14da35b925856/src/main/java/ru/netology/javaqateam/repository/GameStore.java#L35-L36
# Шаги воспроизведения

1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/gamestore) в IDEA
2. Запустить в отладочном режиме тест `shouldContainsGameTest` в классе `GameStoreTest`.
3. Пошагово выполнить строку `assertTrue(store.containsGame(game));`
4. Убедится что в методе `containsGame(Game game)` класса `GameStore` не заходим внутрь цикла .

*Ожидаемый результат:* При тестировании метода `containsGame(Game game)` класса `GameStore` с тестом `shouldContainsGameTest` в классе `GameStoreTest` получаем значение `true`
*Фактический результат:* При тестировании метода `containsGame(Game game)` класса `GameStore` с тестом `shouldContainsGameTest` в классе `GameStoreTest` получаем значение `false`
# Скриншот
![image](https://user-images.githubusercontent.com/113417128/204800437-f6431244-dfd7-475e-8d60-df822e38d6aa.png)
# Окружение
* **Desktop, Windows 10 (Home x64), Версия 21H2
* **IDE:**IntelliJ IDEA 2022.2.2 (Community Edition)
* **Java:**OpenJDK 11

**Comment by shvisor** [comment]
Счетчик исправлен, получаем значение `true`
