### ISSUE TITLE
Не суммируется время игрока за игрой каталога

### ISSUE THREAD

**Issue by MaratGP1967** [MaratGP1967/javaqa-team-diplom#2]
# Описание
Не выполняется суммирование количества времени, которое игрок проиграл за игрой каталога  в методе `addPlayTime` класса `GameStore` (стр. 50)

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/4a30451cf2f4132fa063af5bd1a14da35b925856/src/main/java/ru/netology/javaqateam/repository/GameStore.java#L50

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/gamestore) в IDEA
2. Запустить в отладочном режиме тест `shouldGetSumPlayedTimeTest` в классе `GameStoreTest`.
3. Пошагово выполнить строки 33-35 и остановиться на 37строке теста `shouldGetSumPlayedTimeTest` в классе `GameStoreTest` 
4. Посмотреть внизу консоли что суммирование количества времени не выполняется.

*Ожидаемый результат:* При запуске теста `shouldGetSumPlayedTimeTest` класса `GameStoreTest` выполняется суммирование количества времени методом `addPlayTime` класса `GameStore`

*Фактический результат:* При запуске теста `shouldGetSumPlayedTimeTest` класса `GameStoreTest` не выполняется суммирование количества времени методом `addPlayTime` класса `GameStore`

# Скриншот
![image](https://user-images.githubusercontent.com/113417128/204810849-0243a1d2-c324-457e-9188-b35bb840982d.png)

# Окружение
* **Desktop, Windows 10 (Home x64), Версия 21H2
* **IDE:**IntelliJ IDEA 2022.2.2 (Community Edition)
* **Java:**OpenJDK 11 сборка), (64 бит)

**Comment by shvisor** [comment]
Время игрока за игрой каталога суммируется
