### ISSUE TITLE
Не суммируется общее количество времени всех игроков

### ISSUE THREAD

**Issue by MaratGP1967** [MaratGP1967/javaqa-team-diplom#3]
# Описание
Метод `getSumPlayedTime` класса `GameStore` не выполняет условия ТЗ, не суммирует общее количество времени всех игроков, проведённого за играми каталога

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/4a30451cf2f4132fa063af5bd1a14da35b925856/src/main/java/ru/netology/javaqateam/repository/GameStore.java#L77

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/gamestore) в IDEA
2. Запустить в отладочном режиме тест `shouldGetSumPlayedTimeTest` в классе `GameStoreTest`.
3. Остановиться на строке 40 - ` Assertions.assertEquals(expected, actual);`
4. Посмотреть что результат выполнения метода `getSumPlayedTime()` класса `GameStore` в строке 38 теста `shouldGetSumPlayedTimeTest` в классе `GameStoreTest` равен нулю.

*Ожидаемый результат:* При тестировании метода `getSumPlayedTime()` класса `GameStore` с тестом `shouldGetSumPlayedTimeTest` в классе `GameStoreTest` получаем значение `9`

*Фактический результат:* При тестировании метода `getSumPlayedTime()` класса `GameStore` с тестом `shouldGetSumPlayedTimeTest` в классе `GameStoreTest` получаем значение `0`

# Скриншот
![image](https://user-images.githubusercontent.com/113417128/204815872-b3bae779-f173-44ef-88e5-1a968462b6b2.png)

# Окружение
* **Desktop, Windows 10 (Home x64), Версия 21H2
* **IDE:**IntelliJ IDEA 2022.2.2 (Community Edition)
* **Java:**OpenJDK 11 сборка), (64 бит)

**Comment by shvisor** [comment]
Общее время для всех игроков суммируется
