### ISSUE TITLE
Не суммируется время игр одного жанра

### ISSUE THREAD

**Issue by shvisor** [MaratGP1967/javaqa-team-diplom#4]
# Описание
В методе `play` класса `Player` (строка 41) в мапу не добавляется время игры определенного жанра. В следствие чего метод `sumGenre` классa `Player` возвращает не корректное значение (0)

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/4a30451cf2f4132fa063af5bd1a14da35b925856/src/main/java/ru/netology/javaqateam/repository/Player.java#L48

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/main/src) в IDEA
2. В классе `PlayerTest` запускаем тест `shouldSumGenreIfOneGame` 
3. Устанавливаем точку останова на строке 17 и пошагово проходим код отладчиком до строки 48 метода `play` класса `Player`.
4. Посмотреть на вывод консоли, количество времени не изменилось.

*Ожидаемый результат:* При запуске теста `shouldSumGenreIfOneGame` в классе `PlayerTest` выполняется суммирование игр определенного жанра методом `sumGenre` классf `PlayerTest`.
*Фактический результат:* При запуске теста `shouldSumGenreIfOneGame` в классе `PlayerTest` не выполняется суммирование игр определенного жанра методом `sumGenre` класса `Player` из-за не добавления времени игры в мапу в методе `play` класса `Player`.

# Скриншот
![image](https://user-images.githubusercontent.com/113560499/205748199-fd8e8e17-d871-4ea0-b830-5f95b487b248.png)

# Окружение
* **Операционная система:** Windows 10 Pro 19044.2006
* **IDE:** IntelliJ IDEA 2022.2.2 (Communiti Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.16

**Comment by MaratGP1967** [comment]
Внесены изменения в метод play класса Player что бы суммировалось время игр одного жанра. 
Метод поправлен в соответствии с заданием:
     * игрок играет в игру game на протяжении hours часов
     * об этом нужно сообщить объекту-каталогу игр, откуда была установлена игра
     * также надо обновить значения в мапе игрока, добавив проигранное количество часов
     * возвращает суммарное количество часов, проигранное в эту игру.
     * если игра не была установлена, то надо выкидывать RuntimeException
