### ISSUE TITLE
Отсутствует исключение RuntimeException

### ISSUE THREAD

**Issue by shvisor** [MaratGP1967/javaqa-team-diplom#5]
# Описание
Метод `play` касса `Player` не выкидывает исключение `RuntimeException` в случае, если игра не установлена

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/fedbc25a8f558f6993456855abfcaea6b072e495/src/main/java/ru/netology/javaqateam/repository/Player.java#L41-L49

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/main/src) в IDEA
2. Запустить тест `shouldException` класса `PlayerTest` (строка 44)
3. Посмотреть на вывод консоли

*Ожидаемый результат:* Тест проходит, исключение выводится.
*Фактический результат:* Тест падает, т.к. в методе `play` касса `Player` отсутствует условие для вывода исключения.

# Скриншот
![image](https://user-images.githubusercontent.com/113560499/205904562-e7aa13fe-333d-43a9-b869-b2200a4fc26e.png)

# Окружение
* **Операционная система:** Windows 10 Pro 19044.2006
* **IDE:** IntelliJ IDEA 2022.2.2 (Communiti Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.16

**Comment by MaratGP1967** [comment]
Исключение `RuntimeException` в методе `play` класса `Player` реализовано для случая отсутствия инсталляции игры.
