### ISSUE TITLE
Отсутствует код в методе

### ISSUE THREAD

**Issue by shvisor** [MaratGP1967/javaqa-team-diplom#6]
# Описание
В методе `mostPlayerByGenre` класса `Player` (строка 71) отсутствует код.

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/fedbc25a8f558f6993456855abfcaea6b072e495/src/main/java/ru/netology/javaqateam/repository/Player.java#L71-L73

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/main/src) в IDEA
2. Спуститься к  методу `mostPlayerByGenre` класса `Player` (строка 71)
3. Удостовериться в отсуствии кода

*Ожидаемый результат:* Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего. Если в игры этого жанра не играли, возвращается null
*Фактический результат:* Код метода отсутствует, метод возвращает null

# Скриншот
![image](https://user-images.githubusercontent.com/113560499/205906400-cd05ac0f-0cdb-4227-856e-f4359916091a.png)

# Окружение
* **Операционная система:** Windows 10 Pro 19044.2006
* **IDE:** IntelliJ IDEA 2022.2.2 (Communiti Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.16

**Comment by MaratGP1967** [comment]
В методе `mostPlayerByGenre` класса `Player` реализована логика поиска игры по жанру, в которую играли больше всего.
