### ISSUE TITLE
Не суммируется время потраченное игроком на игру одного жанра

### ISSUE THREAD

**Issue by shvisor** [MaratGP1967/javaqa-team-diplom#7]
# Описание
В методе `sumGenre` класса `Player` не суммируется время игр одного жанра проигранных игроком

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/b5a8eccb7a6cb16558147098a777357e830b7454/src/main/java/ru/netology/javaqateam/repository/Player.java#L57-L67

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/player/src) в IDEA
2. В тесте `shouldSumGenreIfSeveralGame` класса `PlayerTest` ставим точку останова на строке 30
3. Пройти дебаггером по тесту.
4. Пройти дебаггером до метода `sumGenre`
5. Посмотреть на вывод консоли

*Ожидаемый результат:* Время проигранное в двух играх жанра Action суммируется
*Фактический результат:* Указано время только одной игры, после перебора циклом игры другого жанра счетчик времени обнулился.

# Скриншот
![image](https://user-images.githubusercontent.com/113560499/205979658-dab1feaa-dba3-43a9-8188-d7c59c64fc6c.png)

# Окружение
* **Операционная система:** Windows 10 Pro 19044.2006
* **IDE:** IntelliJ IDEA 2022.2.2 (Communiti Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.16

**Comment by MaratGP1967** [comment]
Настроен метод `sumGenre` в классе `Player`. Время игр одного жанра проигранных игроком суммируется.
