### ISSUE TITLE
Происходит обновление игры

### ISSUE THREAD

**Issue by shvisor** [MaratGP1967/javaqa-team-diplom#8]
# Описание
При выполнении метода `installGame` класса `Player` происходит обновление игры, но по условию, если у игрока уже есть такая игра, никаких изменений быть не должно.

# Локация дефекта
https://github.com/MaratGP1967/javaqa-team-diplom/blob/3910ba6be2758f04f34d78387f863d567a28779a/src/main/java/ru/netology/javaqateam/repository/Player.java#L30-L32

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/MaratGP1967/javaqa-team-diplom/tree/player/src/main/java/ru/netology/javaqateam) в IDEA
2. Устанавливаем точку останова в тесте `shouldInstallIfGameExist` класса `PlayerTest` и проходим пошагово дебаггером по коду
3. Посмотреть на вывод консоли в методе `installGame` класса `Player` (строка 31)

*Ожидаемый результат:* Вторая игра не должна устанавливаться в случае, если у игрока такая игра уже есть.
*Фактический результат:* При установке второй игры данные перезаписываются и игра заменяется на такую же с новыми параметрами (время игры)

# Скриншот
![image](https://user-images.githubusercontent.com/113560499/206154850-0bdf9a0f-9873-4ea5-9d77-cdc48718cec7.png)

# Окружение
* **Операционная система:** Windows 10 Pro 19044.2006
* **IDE:** IntelliJ IDEA 2022.2.2 (Communiti Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.16

**Comment by MaratGP1967** [comment]
Изменен метод `installGame` класса `Player`, в новой версии проверяется была ли установлена игра, что бы не затирать в мапе уже существующие значение.
